---
author: Masumbuko Semba
date: '2020-03-06'
slider: true
slug: northeast-monsoon-season-oceanographic-insitu-data-collection
categories: []
tags:
  - sapphire
banner: banners/sapphire_1.png
title: Northeast Monsoon Season Oceanographic Insitu Data Collection
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, comment = "")
```


```{r}
require(tidyverse)
require(sf)
require(leaflet)
```

On 3^rd^ March, 2020, a team of researcher led by Prof. Nthahondi Nyandwi started a three day oceanographic data gathering in the Pemba Channel. The team launched an ADCP equipment from Kigombe, to measure ocean current's speed and direction.  

```{r fig1, fig.cap="Ocean current measured from ADCP", fig.height=3.0, fig.width=8.5}
transect1 = readxl::read_excel("e:/Data Manipulation/Kagera/data/adp/Day 1/Matlab/Transect No1_LB-RB.xlsx", sheet = 3)

transect1 = transect1%>% 
  na_if(-9999)  %>% 
  select(easting = 2, northing = 3, depth = 4, 
         distance = 5, bottom.depth = 6, u = 7, v = 8) %>% 
  mutate(u = u/100, v = v/100, speed = sqrt(u^2 + v^2))

ggplot() +
  metR::geom_contour_fill(data = transect1 %>% filter(!is.na(speed)), 
            aes(x = distance, y = depth, z = speed),bins = 20, na.fill = TRUE) +
  scale_y_reverse(breaks = seq(0,4,.5))+
  scale_fill_gradientn(colours = oce::oce.colors9A(120))+
  coord_cartesian(expand = FALSE) +
  cowplot::theme_cowplot()+
  labs(x = "Distance from edge [m]", y = "Water depth [m]") +
  guides(fill = guide_colorbar(title = expression(Current~speed~(ms^{-1})),direction = "vertical", title.position = "right", title.hjust = .5, nbin = 12, draw.ulim = TRUE, reverse = TRUE,raster = FALSE,draw.llim = TRUE,barheight = unit(5, "cm"), title.theme = element_text(angle = 90)))
```


